### ISSUE TITLE
TemplateNotFound: !page.html

### ISSUE THREAD

**Issue by pbauer** [testthedocs/cookiecutter-plone-training#2]
I installed cookiecutter in a python3 virtualenv and got this. Same when I install with homebrew. 

```
(cookiecutter-plone-training)  pbauer@bullet  ~/workspace  cookiecutter cookiecutter-plone-training
project_name [Name of the training]: Angular SDK
short_description [A short description which will be used in the README]: Building Angular 4 apps using the Plone REST API.
version_nr [0.1]:
Select training_level:
1 - All levels
2 - Experienced
Choose from 1, 2 [1]:
project_slug [angular-sdk]: angular
Traceback (most recent call last):
  File "/Users/pbauer/workspace/cookiecutter-plone-training/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/cookiecutter/generate.py", line 349, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/cookiecutter/generate.py", line 172, in generate_file
    rendered_file = tmpl.render(**context)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./_templates/page.html", line 1, in top-level template code
  File "/Users/pbauer/workspace/cookiecutter-plone-training/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: !page.html
```

**Comment by svx** [comment]
@pbauer fixed !
